version: "3.1" 
services:

    mysql:
      image: ubuntu/mysql
      container_name: ${PROJECT_NAME}-mysql
      volumes:
         - "./sourcefiles/mysql:/var/lib/mysql"
      environment:
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      ports:
       - "30306:3306"
      networks:
            testing_net:
                ipv4_address: 172.28.1.2
    webserver:
      image: nginx:alpine
      container_name: ${PROJECT_NAME}-webserver
      working_dir: /application
      volumes:
          - /var/www/html/energyportal:/application
          - ./sourcefiles/nginx:/etc/nginx/conf.d
      ports:
       - "8010:8010"
      networks:
            testing_net:
                ipv4_address: 172.28.1.3

    php-fpm:
      build: sourcefiles/php-fpm
      container_name: ${PROJECT_NAME}-php-fpm
      working_dir: /application
      volumes:
        - /var/www/html/energyportal:/application
        - ./sourcefiles/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
        - ./sourcefiles/php-fpm/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
      networks:
          testing_net:
              ipv4_address: 172.28.1.4
networks:
    testing_net:
        ipam:
            driver: default
            config:
                - subnet: 172.28.0.0/16